### ISSUE TITLE
AOSiP Pie manifest: snippets/lineage.xml is no longer in synch with LOS (chromium-webview problem)

### ISSUE THREAD

**Issue by jer194** [AOSiP/platform_manifest#15]
```
AOSiP still has (in snippets/lineage.xml):
<project path="external/chromium-webview" name="android_external_chromium-webview" clone-depth="1" remote="los" />

LOS has now:
<project path="external/chromium-webview" name="LineageOS/android_external_chromium-webview" groups="pdk" clone-depth="1" revision="master" />

Thus, in AOSiP snippets/lineage.xml it should be changed to:
<project path="external/chromium-webview" name="android_external_chromium-webview" clone-depth="1" remote="los" revision="master" />
```
xref:
https://forum.xda-developers.com/t/rom-9-0_r44-arm64-android-open-source-illusion-project-athene-unofficial.3889942/page-25#post-84588229

**Comment by aoleary** [comment]
Hi @jer194 Thanks for the info. Makes my job a lot easier :-)
I have pushed the fixes for the February Security Patch to the AOSiP gerrit.

I've also pushed the March Security Patch this morning.
And finally, I've also pushed some extra features to the Pie branch

**Comment by jer194** [comment]
Excellent, thanks a lot, for keeping Pie up to date!
