### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [AOSiP/platform_manifest#9]
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: hardware/qcom/sm8150/display/Android.bp:4:1: unrecognized module type "display_go_defaults"
23:18:41 soong bootstrap failed with: exit status 1

why

**Comment by xlxfoxxlx** [comment]
should be fine now
